vrrp_instance VI_1 {
  state MASTER
  interface eth0
  virtual_router_id 51
  priority 101          # priorità alta in quanto master
  advert_int 1          # heartbeat ogni secondo

  # unicast altrimenti Docker mi distrugge il multicast di default
  unicast_src_ip 172.20.0.10
  unicast_peer {
    172.20.0.11
  }

  authentication {
    auth_type PASS
    auth_pass dok_ha_secret
  }

  virtual_ipaddress {
    172.20.0.100
  }
}